[cosmic-ray]
module-path = "advanced_testing_techniques/quicksort.py"
timeout = 10.0
excluded-modules = []
test-command = "python -munittest tests/test_quicksort_bad.py"

[cosmic-ray.distributor]
name = "local"
